name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pandaman64/isabelle-action@v1.1
        with:
          args: build -d . Morse
